(defproject {{name}} "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"

   :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.openscience.cdk/cdk-annotation "1.5.5"]
                 [org.openscience.cdk/cdk-atomtype "1.5.5"]
                 [org.openscience.cdk/cdk-builder3d "1.5.5"]
                 [org.openscience.cdk/cdk-builder3dtools  "1.5.5"]
                 [org.openscience.cdk/cdk-charges "1.5.5"]
                 [org.openscience.cdk/cdk-cip "1.5.5"]
                 [org.openscience.cdk/cdk-control "1.5.5"]
                 [org.openscience.cdk/cdk-core "1.5.5"]
                 [org.openscience.cdk/cdk-data "1.5.5"]
                 [org.openscience.cdk/cdk-datadebug "1.5.5"]
                 [org.openscience.cdk/cdk-dict "1.5.5"]
                 [org.openscience.cdk/cdk-diff "1.5.5"]
                 [org.openscience.cdk/cdk-extra "1.5.5"]
                 [org.openscience.cdk/cdk-fingerprint "1.5.5"]
                 [org.openscience.cdk/cdk-forcefield "1.5.5"]
                 [org.openscience.cdk/cdk-formula "1.5.5"]
                 [org.openscience.cdk/cdk-fragment "1.5.5"]
                 [org.openscience.cdk/cdk-group "1.5.5"]
                 [org.openscience.cdk/cdk-hash "1.5.5"]
                 [org.openscience.cdk/cdk-inchi "1.5.5"]
                 [org.openscience.cdk/cdk-interfaces "1.5.5"]
                 [org.openscience.cdk/cdk-io "1.5.5"]
                 [org.openscience.cdk/cdk-ioformats "1.5.5"]
                 [org.openscience.cdk/cdk-ionpot "1.5.5"]
                 ;;[org.openscience.cdk/cdk-iordf "1.5.5"]
                 [org.openscience.cdk/cdk-isomorphism "1.5.5"]
                 [org.openscience.cdk/cdk-libiocml "1.5.5"]
                 [org.openscience.cdk/cdk-libiomd "1.5.5"]
                 [org.openscience.cdk/cdk-log4j "1.5.5"]
                 [org.openscience.cdk/cdk-pcore "1.5.5"]
                 [org.openscience.cdk/cdk-pdb "1.5.5"]
                 [org.openscience.cdk/cdk-pdbcml "1.5.5"]
                 [org.openscience.cdk/cdk-qm "1.5.5"]
                 [org.openscience.cdk/cdk-qsar "1.5.5"]
                 [org.openscience.cdk/cdk-qsaratomic "1.5.5"]
                 [org.openscience.cdk/cdk-qsarbond "1.5.5"]
                 [org.openscience.cdk/cdk-qsarcml "1.5.5"]
                 [org.openscience.cdk/cdk-qsarionpot "1.5.5"]
                 [org.openscience.cdk/cdk-qsarmolecular "1.5.5"]
                 [org.openscience.cdk/cdk-qsarprotein "1.5.5"]
                 [org.openscience.cdk/cdk-reaction "1.5.5"]
                 [org.openscience.cdk/cdk-render "1.5.5"]
                 [org.openscience.cdk/cdk-renderawt "1.5.5"]
                 [org.openscience.cdk/cdk-renderbasic "1.5.5"]
                 [org.openscience.cdk/cdk-renderextra "1.5.5"]
                 [org.openscience.cdk/cdk-signature "1.5.5"]
                 [org.openscience.cdk/cdk-silent "1.5.5"]
                 [org.openscience.cdk/cdk-smarts "1.5.5"]
                 [org.openscience.cdk/cdk-smiles "1.5.5"]
                 [org.openscience.cdk/cdk-standard "1.5.5"]
                 [org.openscience.cdk/cdk-structgen "1.5.5"]
                 [org.openscience.cdk/cdk-tautomer "1.5.5"]
                 [org.openscience.cdk/cdk-valencycheck "1.5.5"]
                 [org.openscience.cdk/cdk-qm "1.5.5"]
                 [org.openscience.cdk/cdk-qsar "1.5.5"]
                 [org.openscience.cdk/cdk-qsaratomic "1.5.5"]
                 ]

  :main ^:skip-aot testmaven.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}}
  :repositories [["ebi-repo" "http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo" ]
                 ["cdk1" "http://ambit.uni-plovdiv.bg:8083/nexus/index.html"]
                 ["cdk2" "https://maven.ch.cam.ac.uk/"]]  :source-paths ["src"]
)

